# Generated by Django 4.2.23 on 2025-10-28 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_product_country_of_origin'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('email', 'email'), ('phone', 'phone')], max_length=10)),
                ('target_value', models.CharField(max_length=255)),
                ('salt', models.CharField(max_length=32)),
                ('otp_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.IntegerField(default=0)),
                ('verified', models.BooleanField(default=False)),
                ('meta', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
